lib/seira/pods.rb, lib/seira/random.rb
Renamed the existing `run` command to `connect`; `run` now runs a specified bash command in a temporary pod, and `connect` opens a bash session on an existing pod.
Example usages:
`seira internal specs pods run rails console`
`seira staging office pods run rake routes`
`seira staging detective pods run "pwd && ls"`
=> Allow running one-off commands

.gitignore, lib/seira/secrets.rb
If you create a new db and want to promote it to primary, there's no way to do that currently without knowing about the internals of how pgbouncer secrets are set up; this allows updating that config at the same abstraction level you have when creating it
=> Allow overriding pgbouncer-secrets if it already exists

lib/seira/secrets.rb, spec/secrets_spec.rb
Apparently the issue wasn't just newlines at the end of the string; ruby's Base64 library puts newlines in the middle as well, which kubernetes is not happy with
=> Actually fix secrets

lib/seira/db.rb
Fixes https://app.clubhouse.io/handshake/story/31633/migrating-fails-if-requires-superuser. By removing superuser we removed the ability to run `rails db:migrate` and create extensions.
=> do not remove superuser from proxyuser

lib/seira.rb, lib/seira/db.rb, lib/seira/db/create.rb, lib/seira/secrets.rb, lib/seira/settings.rb, spec/seira_spec.rb
- Allow for creating replicas
- Auto-create unique pgbouncer deployment configs for every new DB
- Allow creating primaries as HA
- Always enable auto backups if primary
- Makes https://app.clubhouse.io/handshake/story/30969/create-pgbouncer-secret-should-be-able-to-override-the-secret-if-it-s-already-set irrelevant
- Finishes https://app.clubhouse.io/handshake/story/30649/generate-pgbouncer-yaml-when-creating-a-new-database
- Finishes https://app.clubhouse.io/handshake/story/31696/add-flag-for-ha-postgres
- Finishes https://app.clubhouse.io/handshake/story/31637/turn-on-automated-backups-by-default
=> More db generation features

lib/seira/app.rb, lib/seira/version.rb
Pretty quick-and-dirty but it works
Running `app restart` is an easy way to see what the output will look like
=> Monitor rollouts after apply

lib/seira/app.rb
This was broken by the new `jobs` directory
=> Fix scale command

lib/seira.rb, lib/seira/cluster.rb, lib/seira/memcached.rb, lib/seira/node_pools.rb
The goal here is more granular control over cluster upgrades, node pool changes, and generally managing node pools.
A few advantages:
- easier to do node pool changes such as instance size
- can be more careful during upgrades, which is already generally scary
- can build up more micro functionality on top of these smaller actions
Mostly this was moving code from your original method into this new file :)
=> more granular control over node pools

lib/seira/pods.rb, lib/seira/version.rb
This assumes that each app has a `terminal` deployment which is set up for the purpose of exec-ing into.
Rather than having two separate `pods run` and `pods connect` commands, this just has `pods connect` and allows specifying a `--dedicated` flag which operates similarly to how `pods run` did. Both these methods have their merits (e.g. non-dedicated connects super quickly; dedicated doesn't get kicked out due to deploys), but non-dedicated is a more reliable default.
The functionality from `pods run --detached` has been replaced by `jobs run`.
=> Refactor pods connect/run

lib/seira/jobs.rb
If you're trying set shell variables in a command like `LOG_LEVEL=debug rake some_task`, the `LOG_LEVEL=debug` part ends up being interpreted as the executable and crashes. Trying to route around this with `jobs run bash -c "LOG_LEVEL=debug rake some_task"` ends up being equivalent to running `bash -c LOG_LEVEL=debug`, due to the logic of splitting on spaces and passing every piece as a separate argument.
Treating the command as just a one-piece string and wrapping with `sh -c` allows using a more natural syntax to run commands like this.
=> Run job as shell command

lib/seira/settings.rb
Break the dependency of having to run seria from within the directory the config file is defined
=> Allow specifying config file location with ENV variable

lib/seira/app.rb, lib/seira/settings.rb
This could help protect against accidental local deploys
=> warn users if running apply, and an ENV is not present

lib/seira/pods.rb, spec/pods_spec.rb
Siera returns fails with a Ruby exception:
* Attempting to connect to a pod in an existing application, and
* Not creating a dedicated pod, and
* No pods are currently running in the specified tier (or 'terminal', if none specified).
This change handles this condition in the same way other, related failures are handled. An error message is printed, and Siera exits with status code 1.
=> fix(pods): Add error for no pods available

lib/seira/app.rb, lib/seira/cluster.rb, lib/seira/version.rb
we no longer need to bootstrap clusters because we don't use `gcr-secret` or `cloudsql-credentials`
for apps, we only need to bootstrap the main secret
=> bootstrap no cloudsql

lib/seira/db.rb, lib/seira/db/alter_proxyuser_roles.rb, lib/seira/db/create.rb, lib/seira/version.rb
The only workaround I could get working after spending way too long on this was to manually whitelist the correct IP in the gcloud UI after the initial attempt fails and then running the db create command with the `--alter-proxy-user-roles-only` flag
`seira demo2 student-backend db create --alter-proxy-user-roles-only`
https://joinhandshake.slack.com/archives/C2PJL2NHL/p1545262385133200?thread_ts=1545166325.122000&cid=C2PJL2NHL
Can't spend any more time on this now but at least the description can potentially unblock others in case they need to spin up new dbs before we get a better fix in place.
=> update db creation script

lib/seira.rb
When `kubectl version` is run, it phones home to check what version exists on the server. At best, this creates some lag waiting for the HTTP call. At worst, the remote is unavailable (causing `kubectl version` to return a non-zero exit status), and `seira` incorrectly interprets that as `kubectl` not being installed properly.
This change adds the `-c` flag to that check, which suppresses the call to the remote server. This should speed up `seira` start time and prevent complete failure if the remote is unavailable.
=> Don't check server version of kubectl on launch

lib/seira.rb, lib/seira/commands/gcloud.rb, lib/seira/node_pools.rb, lib/seira/settings.rb, lib/seira/version.rb
Apply `--region` to all commands to fix:
```
ERROR: (gcloud.container.node-pools.list) One of [--zone, --region] must be supplied: Please specify location.
```
=> Add Region to Node Pool Commands

lib/helpers.rb, lib/seira.rb, lib/seira/db.rb, lib/seira/db/create.rb, lib/seira/version.rb
Fixing newly failing command `create_readonly_user` and adding support for `seira version` for easier troubleshooting.
⚠️ I need to clean the duplicated code for extracting private_ips.
=> Fix create_readonly_user

lib/seira.rb
`kubectl version` does not accept `-c` anymore. 
```
› kubectl version -c                                                          
Error: unknown shorthand flag: 'c' in -c
```
See [relevant PR](https://gitlab.cncf.ci/kubernetes/kubernetes/commit/db7c8f633b4d53f356cdca7d257898df581c9aa8).
Let's use `kubectl version --client` instead.
```
› kubectl version --client                                                    
Client Version: version.Info{ ... }
```
=> kubectl version -c has been deprecated, use --client instead

lib/seira/jobs.rb, lib/seira/util/resource_renderer.rb, lib/seira/version.rb
With default still of `1`, allow to pass a customized parallelism using ERB templating
=> Allow parallel template jobs

lib/helpers.rb, lib/seira/db.rb, lib/seira/db/create.rb, lib/seira/version.rb
Now that we're configuring our database instances via terraform we don't need to do it via `seira`. However, `seira` would take care of user and secret management, which we still do need.
This PR adds support for configuring an existing database instance.
We also noticed the helper that determines the rails environment uses the context cluster name which is not a safe assumption to make.
=> add db configure action

lib/seira/jobs.rb, lib/seira/version.rb
Not everything has an active deployment, so we should allow passing in a revision as an ENV in that case.
=> Fix Jobs With No Web Tier

README.md, lib/helpers.rb, lib/seira/db.rb, lib/seira/version.rb
Currently we fetch a secret, parse out a key's value, and then use the host of the URI to calculate the primary database name.
That has two issues:
* Guess work
* Requires access
This introduces a file that will be in each app's folder to define some of these things to remove guess work and access requirements.
=> Introduce new app config files for removing guess work

README.md, lib/seira/pods.rb
Thanks for providing this! This library has made my life much easier today. 😁 
I noticed the README suggested `pod run` as a valid command, but internally the required `run_run` command wasn't implemented. Maybe this is some loose copy-paste artifact from `lib/seira/jobs.rb`? ✂️ 
This change trims the broken command off the `pods` module & updates the README to accurately demonstrate connecting to a running pod.
Please let me know if I've misunderstood the intent here! 🕵️ I'd love to understand things better if there's something I've missed.
=> Remove unused 'run' command on pods.

.travis.yml, README.md
The test suite needed to migrate from travis-ci.org (deprecated / turned off) to travis-ci.com. I also upped the test suite ruby version.
=> Clean up test suite
